# Generated by Django 5.1.6 on 2025-02-11 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Communitie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, verbose_name='Название')),
                ('description', models.TextField(max_length=150, verbose_name='Описание')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('free', models.BooleanField()),
                ('banner', models.ImageField(blank=True, default='fallback.png', upload_to='', verbose_name='Изображение')),
                ('author', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
