# Generated by Django 5.1.6 on 2025-02-11 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitie',
            name='free',
            field=models.BooleanField(default=True),
        ),
    ]
